version: '3.1'

services:

  mongo:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
          - ./mysql-datadir:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 's5z4aw'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: s5z4aw

  web:
      image: nginx:1.15
      ports:
          - "8080:80"
      volumes:
          - ./code:/code
          - ./default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php

  php:
      image: my-custom-docker-php-fpm:latest
      volumes:
          - ./code:/code
      links:
          - mongo

  redis:
    image: redis:6.2.3-alpine
    ports:
        - "6379:6379"
    volumes:
        - ./redvol:/data